version: '3.8'

services:
  php-app-spidest:
    image: ${IMAGE_NAME}
    container_name: php-app-spidest
    labels:
      - "app=webspidest"
    ports:
      - "9000:9000"
    volumes:
      - /home/pesantech/projects/web-spidest:/app
    networks:
      - app-network
      - pesantech-network

  nginx-app-spidest:
    image: nginx:alpine
    container_name: nginx-app-spidest
    labels:
      - "app=webspidest"
    ports:
      - "80:80"
    volumes:
      - /home/pesantech/projects/web-spidest:/app
      - /home/pesantech/projects/web-spidest/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-app-spidest
    networks:
      - app-network
      - pesantech-network

networks:
  app-network:              # DB network posgres
    driver: bridge
  pesantech-network:         # ← reverse proxy
    name: pesantech-network
